service: scraper

useDotenv: true

frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - s3:PutObject
            - s3:GetBucketLocation
          Resource: "*"
functions:
  fetch-podcasts:
    handler: lambdas/scrape-data/handler.run
    events:
      # Invoke Lambda function every 23 hours
      - schedule: rate(23 hours)
  get-list:
    handler: lambdas/get-podcasts/handler.run
    events:
      - http:
          path: /podcasts
          method: GET
          request:
            parameters:
              querystrings:
                date: true
          cors: true
